name: build
on: 
  pull_request: ~
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 'PHP-7.4'
          - 'PHP-8.0.0'
    steps:
      - uses: actions/checkout@v2
      - run: make pull
      - run: echo PHP_BRANCH=${{ matrix.php }} >> .env
      - run: make
        timeout-minutes: 30
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.php }}-web.wasm
          path: |
            build/php-web.wasm
            build/php-web.js
